### ISSUE TITLE
Hyperline plugins selection doesn't work.

### ISSUE THREAD

**Issue by noook** [Hyperline/hyperline#167]
Hyperline plugins are not the same as specified in my config file (only relevant options): 
```js
module.exports = {
  config: {
    updateChannel: 'canary',
    shell: '/bin/zsh',
    shellArgs: ['--login'],
    env: {
      LANG: "fr_FR.UTF-8"
  },

  hyperline: {
    plugins: [
      "hostname",
      "uptime",
      "ip",
      "memory",
      "cpu",
      "network",
      "battery",
      "time",
      "spotify"
    ]
  },

  plugins: ["hyper-one-dark", "hyper-pane", "hyperline"],
  localPlugins: [],
};
```

Every time I save or even change the order of the plugins it doesn't make any change.

Hyper 2.1.0-canary.2 (canary)
Plugins: 
  hyper-one-dark (1.0.0),
  hyper-pane (2.1.3),
  hyperline (1.2.0)

MacOS 10.13.6

**Comment by AuHau** [comment]
I am not sure what exactly you mean, but you have in your list plugins, which seems not supported atm. For example `time` or `uptime`. Or at least I assume they are unsupported because they are commented out from https://github.com/Hyperline/hyperline/blob/master/src/lib/plugins/index.js

I would be actually interested why they are commented because I would like to have for example support for the Time plugin.

**Comment by liloow** [comment]
@AuHau @neilrichter The project seems to be on hold at the moment, but I you can check my fork, I fixed a few things: [HERE](https://github.com/liloow/hyperline/)
Disclaimer: I only fixed what I needed for my personal use but and tweaked a few things like colors but who knows, it might suit your needs

**Comment by cfvescovo** [comment]
> @AuHau @neilrichter The project seems to be on hold at the moment, but I you can check my fork, I fixed a few things: [HERE](https://github.com/liloow/hyperline/)
> Disclaimer: I only fixed what I needed for my personal use but and tweaked a few things like colors but who knows, it might suit your needs

Unfortunately it does not work.
You can fix this by editing the source code.
