### ISSUE TITLE
Overlapping at Hyperterm default size

### ISSUE THREAD

**Issue by mxdlx** [Hyperline/hyperline#18]
Hyperline overlaps with prompt at bottom of hyperterm (default size), I don't know if retina display resolution has something to do with this. Please let me know if I can do anything to help.
<img width="566" alt="captura de pantalla 2016-08-24 a las 00 14 44" src="https://cloud.githubusercontent.com/assets/3970003/17917127/d3062aac-698f-11e6-9f4f-63aedb52b6bf.png">

**Comment by NickTikhonov** [comment]
Hey @MadlySeason - thanks for reporting the problem :) I could replicate this by slowly changing the height of the window while hyperline was running:

![untitled mov](https://cloud.githubusercontent.com/assets/6755555/17939743/aa910826-6a34-11e6-9068-d977a1af694a.gif)

This could be caused by how the hyperline element overlaps the terminal. The problem would probably be solved if the overlap is removed. I'll take a look at fixing this :)

**Comment by davegomez** [comment]
I think this is not an Hyperline issue since I have experimented this problem even without the extension, I think it might be a Hyperterm issue.

**Comment by timneutkens** [comment]
Open up `.hyperterm.js` and edit the padding propery to this: `padding: '12px 14px 18px 14px'`

**Comment by jdheyburn** [comment]
> Open up `.hyperterm.js` and edit the padding property to this: `padding: '12px 14px 18px 14px'`

Nowadays the file is called `.hyper.js`.
