### ISSUE TITLE
General Design, Feature Discussion

### ISSUE THREAD

**Issue by jerrylopez** [Hyperline/hyperline#4]
Hello! :) I really like you extension. The idea of doing something like this came to mind a couple years back, but I didn't know how to really accomplish it haha. Powerline, and patched fonts were along the lines of what I was thinking, but now that we have HyperTerm I feel like so much is possible. 

I just wanted to see if you have any ideas beyond what you have now? If so, what are they? I would love to see and help. I've always wanted something like this to display important info for me based on different factors or on what I'm currently doing.

**Comment by NickTikhonov** [comment]
Hey @JerryLopez - thanks for the issue and fixing up my `package.json` 🎉 . This project started off as a way for me to learn how to hack HyperTerm - but I intend to turn this into a serious plugin as this could be a great addition to the terminal for a lot of people. I think that the following features are really important regardless of what info we end up showing:

* Custom colors / colors that match those of the terminal window
* Ability to customise what gets shown - perhaps selecting from a list of available items
* Ability to change the order of items on the screen
* Rendering using the DOM instead of canvas graphics (this is the hackiest thing right now :)

It would be great to have more information available for display. Personally I would love to see:

* Upload / download traffic
* Some kind of summary of running / detached processes

Do you have any suggestions for features that would make this plugin more useful for you?

**Comment by JerryLopez** [comment]
@NickTikhonov Ideas I had were a couple that you listed above and:

- Resizable line
- Git information (Branch/Last Commit Id/Staged & Unstaged count)
- Clickable buttons (for example: Editor button used to open current directory in your favorite editor) 
- Something I just thought of is expandable menus or sections to show more options or information

I think by completing the first 4 items on your list that would be a good foundation to accomplish all kinds of stuff with hyperline.

**Comment by NickTikhonov** [comment]
These are all great - I especially like the idea of having git integration and some context menus for accomplishing common tasks. We should provide info that people would otherwise append to their prompt. Perhaps we could also take advantage of having a canvas and render some graphs or other visual elements that would be difficult to keep in the DOM. 

I think these should be the first steps:

* Add linting/transpiling from ES6 and some basic build script
* Match colors to the theme - this info can be extracted from the terminal object
* Define some standard for a single info item, e.g. have separate modules for the hostname, available memory, and so on. Once we have this, we can work on tapping into `.hyperterm.js` and allow the user to configure what gets shown and in what order. 

What do you think?

**Comment by JerryLopez** [comment]
@NickTikhonov will do 👍.  I'll start a pull request as soon as I get a chance for linting and transpiling.

**Comment by timneutkens** [comment]
I'll try
>Match colors to the theme - this info can be extracted from the terminal object
If I get it to render using localPlugin >.<

**Comment by timneutkens** [comment]
To get back at
> Match colors to the theme - this info can be extracted from the terminal object

I finally figured out how to do it. Will fix it shortly 👍

**Comment by davegomez** [comment]
I would like to propose a visual change for Hyperline, adding some icons and blank space.

The icons will be pixel perfect SVGs with original designs related with the type of information displayed by the extension.

I also would like to work adding the network traffic plugin if no one else is working on it already.

![hyperline](https://cloud.githubusercontent.com/assets/282903/17951068/5106e76e-6a2d-11e6-91bc-a8c8ca81585f.png)

If you guys consider this as a good idea I can work on a PR to include it in the extension.

**Comment by timneutkens** [comment]
Hey @davegomez, That's cool 👍 
It's quite hard to detect network traffic. Have looked into it. Only easy way I could come up with is using pcap, but that is kind of crap to do 😉

**Comment by davegomez** [comment]
I think I know a way to do it, let me try and I will make a PR if it success

**Comment by Or3stis** [comment]
How about displaying the battery information as well?
It would be easy to do by periodically running `pmset` on a mac and grep the battery output.
There are similar commands for other OS to make it cross platform.

Should I make a PR?

**Comment by davegomez** [comment]
@Or3stis I can make the icon for the battery and implemented in my icons PR, go ahead.

**Comment by NickTikhonov** [comment]
Started a discussion about user configuration in #30!

**Comment by golodenko** [comment]
Think that idea of having battery, CPU and memory info is to notice unusual behavior.
What do you think of idea to highlight when cpu goes over 80%, battery < 10% and memory is low? 

Like blink once and keep it red to get users attention.
