### ISSUE TITLE
Always show 2 digits for CPU percentage

### ISSUE THREAD

**Issue by jritsema** [Hyperline/hyperline#58]
Hey, awesome plugin!  Thanks for making it!

One suggestion though.  When the cpu percentage changes between 1 digit and 2 digits (e.g.; 9% -> 10%), it creates a rather visually jarring effect when the total width of the status bar grows/shrinks which can be distracting.

What would you think about always using 2 digits (e.g.; 01%, 09%, etc.) ?  That way the width the content in the bar would be constant.

**Comment by davegomez** [comment]
The problem will still exist if the CPU load gets to 100% so in that case we will need three numbers instead of two.

Another solution could be to add the space needed for this numbers but it will create a visual gap between the icon and the displayed data.

I think the best solution in this case would be to place the CPU plugin at the end.

**Comment by jritsema** [comment]
Yes, good point @davegomez.  I like the idea of moving it to the end.  I tried to move it to the end in the config file as well removing it from the config file and it didn't work.  I guess we would need a code change to support it.

**Comment by basedjux** [comment]
This has been revised in #99 

Changed from using percentage to using raw decimal value.
